clubz/config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create]
  resources :clubs
  resources :sessions, only: [:new, :create, :destroy]  

  root 'clubs#index'

end

clubz/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

clubz/app/models/club.rb
class Club < ActiveRecord::Base
  belongs_to :user
end

clubz/app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :clubs

  validates :name, presence: true, uniqueness: true
end

clubz/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

clubz/app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  before_action :require_login, except: [:index]
  before_action :require_ownership, only: [:edit, :update, :destroy]

  def index
    @clubs = Club.all
  end

  def show
    @club = Club.find(params[:id])
    render :show
  end

  def new
    @club = Club.new
  end

  def create
    @club = Club.new(
      name: params[:club][:name],
      description: params[:club][:description],
      user: current_user
    )

    if @club.save
      redirect_to root_path
    else
      flash.now[:alert] = @club.errors.full_messages
      render :new
    end
  end

  def edit
    @club = Club.find(params[:id])
  end

  def update
    @club = Club.find(params[:id])

    if @club && @club.update(name: params[:club][:name], description: params[:club][:description], user: current_user)
      redirect_to root_path
    else
      flash.now[:alert] = @club.errors.full_messages
      render :edit
    end
  end

  def destroy
    @club = Club.find(params[:id])
    @club.destroy
    redirect_to root_path
  end

  def require_login
    unless session[:user_id]
      flash[:alert] = "You must be logged in"
      redirect_to new_session_path
    end
  end

  def require_ownership
    @club = Club.find(params[:id])
    # unless session[:user_id] == @club.user_id
    unless current_user == @club.user
      flash[:alert] = "You are not the owner of this club"
      redirect_to root_path
    end
  end

end

clubz/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(name: params[:name])

    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash.now[:alert] = "Login failed, name and/or password are incorrect"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

clubz/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(
      name: params[:user][:name],
      password: params[:user][:password],
      password_confirmation: params[:user][:password_confirmation]
    )

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash.now[:alert] = @user.errors.full_messages
      render :new
    end
  end

end

clubz/app/helpers/application_helper.rb
module ApplicationHelper
end

clubz/app/helpers/clubs_helper.rb
module ClubsHelper
end

clubz/app/helpers/sessions_helper.rb
module SessionsHelper
end

clubz/app/helpers/users_helper.rb
module UsersHelper
end

clubz/app/views/clubs/_form.html.erb
<%= form_for @club do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <%= f.submit %>
<% end %>

<%= link_to "Back to All Clubs", clubs_path %>

clubz/app/views/clubs/edit.html.erb
<h1>Edit <%= @club.name %></h1>

<%= render 'form' %>

clubz/app/views/clubs/index.html.erb
<h1>Super Exclusive Clubs</h1>

<% if @clubs.count > 0 %>
  <% @clubs.each do |club| %>
    <h3>
      <%= link_to club.name, club_path(club) %>
    </h3>
    <p><%= club.description %></p>
  <% end %>
<% else %>
  <p>No clubs found.</p>
<% end %>

<%= link_to "Open a New Club", new_club_path %>

clubz/app/views/clubs/new.html.erb
<h1>New Club</h1>

<%= render 'form' %>

clubz/app/views/clubs/show.html.erb
<h1><%= @club.name %></h1>

<p>You are authorized for entry! Welcome.</p>

<p><%= link_to "Edit", edit_club_path(@club) %></p>
<p><%= link_to "Delete", club_path(@club), method: :delete %></p>
<p><%= link_to "Back to all clubs", clubs_path %></p>

clubz/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Clubs</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header>
    <% if current_user %>
      <%= link_to "Logout", session_path("current"), method: :delete %>
    <% else %>
      <%= link_to "Login", new_session_path %> |
      <%= link_to "Signup", new_user_path %>
    <% end %>
  </header>

  <% if flash[:alert] %>
    <p>Oops - there were problems with your submission. Please fix the following:</p>
    <ul>
      <% [flash[:alert]].flatten.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <%= yield %>

</body>
</html>

clubz/app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>

  <div>
    <%= f.label :name %> <br />
    <%= f.text_field :name %>
  </div>

  <div>
     <%= f.label :password %><br />
     <%= f.password_field :password %>
  </div>

  <div>
     <%= f.label :password_confirmation %><br />
     <%= f.password_field :password_confirmation %>
  </div>

  <div>
    <%= f.submit "Save" %>
  </div>

<% end %>